Many improvements to the QT script
hypothesis/dev pull request #3
Opened 2020-10-12 13:22 UTC by jon-betts

* Added coverage support
 * Added options to disable linting etc.
 * Added support for projects like 'h'
 * Added support for matching files against tests and vice versa

Looks like the last part was in already, but only in one direction (source -> tests)

2020-10-12 17:40 UTC, seanh requested changes
If I run this in h I get:

    .tox/lint/bin/pylint: not found

It seems to work if I pass `--no-lint`. I think it needs to use flake8 instead of pylint in h.

If I run it in LMS I get:

    /bin/sh: 1: .tox/coverage/bin/coverage: not found

`coverage` is installed in the `tests` env not its own separate env, in lms. It works if I fix that.

I think the script can probably detect what project it's in (via the presence of an `h` or `lms` subdir) and adjust accordingly.

This was a _lot_ shorter and easier to understand before. Aside from the `Run` class and the `argparse` stuff at the bottom, it was just a 26-line `get_files()` func. It's 133 lines longer now. If there's a simpler way to add the new functionality, that'd be nice

2020-10-12 17:40 UTC, seanh commented on bin/qt
> +        action="store_true", help="Verbose output"
These shouldn't be capitalised. This is what `qt --help` prints now:

```
optional arguments:
  -h, --help     show this help message and exit
  -t, --tox      Run commands in tox instead of directly
  --no-lint      Disable linting
  ...
```

The `-h` line, generated by `argparse`, isn't capitalised. Our own lines should follow the standard style
```suggestion
        "-t", "--tox",
        action="store_true", help="run commands in tox instead of directly",
    )
    parser.add_argument(
        "--no-lint",
        action="store_true", help="disable linting"
    )
    parser.add_argument(
        "--no-coverage",
        action="store_true", help="disable coverage"
    )
    parser.add_argument(
        "--no-match",
        action="store_true", help="don't try and match tests to source files"
    )
    parser.add_argument(
        "-v",  "--verbose",
        action="store_true", help="verbose output"
```

2020-10-12 17:40 UTC, seanh commented on bin/qt
> +                    .split()
The formatting has gone weird here:

```suggestion
                subprocess.run(
                    ["git", "diff", "origin/master", "--name-only"],
                    check=True,
                    stdout=subprocess.PIPE,
                )
                .stdout.decode("utf8")
                .split()
```

2020-10-12 17:40 UTC, seanh commented on bin/qt
> +        """Categories the files by what kind of thing they are."""
```suggestion
        """Categorise the files by what kind of thing they are."""
```

2020-10-12 17:40 UTC, seanh commented on bin/qt
> +                    .split()
It looks like the entire file could do with having Black run on it

2020-10-12 17:55 UTC, seanh commented
For adding coverage, with including the corresponding source file in the coverage report even if only its test file has been edited and vice-versa, this seems to work in lms:

```diff
diff --git a/bin/qt b/bin/qt
index 680b21e..ccafb80 100755
--- a/bin/qt
+++ b/bin/qt
@@ -19,12 +19,15 @@ def get_files():
 
     for f in files:
         if f.startswith("tests/"):
-            continue
+            source_file = f[len('tests/unit/'):][:-len('_test.py')] + '.py'
 
-        test_file = "tests/unit/" + os.path.splitext(f)[0] + "_test.py"
+            if source_file not in files:
+                files.append(source_file)
+        else:
+            test_file = "tests/unit/" + os.path.splitext(f)[0] + "_test.py"
 
-        if test_file not in files:
-            files.append(test_file)
+            if test_file not in files:
+                files.append(test_file)
 
     files = [f for f in files if os.path.isfile(f)]
 
@@ -101,7 +104,14 @@ def main():
             run("lint", "pylint", all_test_files, "--rcfile=tests/.pylintrc")
 
         if test_files:
-            run("tests", "pytest", test_files)
+            run("tests", "coverage run -m pytest", test_files)
+            run("tests", "coverage combine", [])
+            run(
+                "tests",
+                "coverage report",
+                [],
+                "--fail-under=0 --no-skip-covered --include " + ",".join(files),
+            )
 
         if functest_files:
             run("functests", "pytest", functest_files)
```

It should probably be using sets for those lists of files.

That doesn't get anything working in h yet. Maybe that's a separate PR? And a less hacky method of constructing a source file name from a test file name would be nice (`source_file = f[len('tests/unit/'):][:-len('_test.py')] + '.py'`). But this is a much smaller diff that just adds the coverage support.

2020-10-12 18:15 UTC, jon-betts commented
I've added on the suggestions from before. It was shorter before but, it didn't work (there were tests classed as source and vice versa in `h`). It was also in kind of dire need of a comment or two. Easier to understand is in the eye of the beholder there.

If you want to hack away on this then go ahead! I'm not precious.

I wonder if it's easier to have two different implementations for the file finder that first say "are you a normal one or a weirdo" and then just splits in two accordingly. Most of the annoying complication comes from having an "if" absolutely everywhere to handle the difference between `/tests/<project>` and `tests/unit/<project>`.

The coverage one is a pain, again we could scan to find likely locations for coverage / binaries first and bail out if none can be found

2020-10-12 18:15 UTC, jon-betts commented
Also, there is a larger point of "do you care?". I don't think we should put too much time into polishing a thing like this.

2020-10-13 11:04 UTC, seanh commented
Could you take a look at <https://github.com/hypothesis/dev/pull/4>?

I think that achieves most of what this PR does, while keeping the code simpler. It gets `qt` working for h and adds coverage support (including finding the source file when only the test file is modified).

I also fixed a couple of long-standing issues with `qt`: it now finds untracked files, and it now runs isort.

I think this PR does include a couple of things that aren't in #4. I think you added support for running `qt` from subdirs of the project root dir, and you added all the `--no`*` options. Maybe those could be sent as follow-up PRs?

2020-10-20 12:40 UTC, jon-betts commented
Superseded

2020-10-20 12:40 UTC, closed without merging